services:
  - type: web
    name: nail-care-api
    env: node
    buildCommand: cd server && npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: nail-care-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    plan: free
